import sharp from 'sharp';
import { readFile, writeFile, mkdir, readdir, copyFile, rm } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';

const SRC = 'public/images/รูปผลงาน';
const OUT = 'public/images/works';
const BAK = 'image-originals/works';
await mkdir(OUT, { recursive: true });
await mkdir(BAK, { recursive: true });

async function collect(dir) {
  const out = [];
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...(await collect(p)));
    else if (/\.jpe?g$/i.test(e.name)) out.push(p);
  }
  return out;
}

// dedupe by content hash; classify by whether parent folder is a รื้อถอน album
const files = (await collect(SRC)).sort();
const seen = new Set();
const demo = [], gen = [];
for (const f of files) {
  const buf = await readFile(f);
  const h = createHash('sha1').update(buf).digest('hex');
  if (seen.has(h)) { console.log('skip dup:', path.basename(f)); continue; }
  seen.add(h);
  const parent = path.basename(path.dirname(f));
  (parent.includes('รื้อ') ? demo : gen).push(buf);
}

async function emit(bufs, prefix) {
  const urls = [];
  for (let i = 0; i < bufs.length; i++) {
    const name = `${prefix}-${String(i + 1).padStart(2, '0')}.jpg`;
    await writeFile(path.join(BAK, name), bufs[i]); // pristine backup
    const out = await sharp(bufs[i]).resize({ width: 1200, withoutEnlargement: true }).jpeg({ quality: 78, mozjpeg: true }).toBuffer();
    await writeFile(path.join(OUT, name), out);
    urls.push(`/images/works/${name}`);
  }
  return urls;
}
const demolitionWorks = await emit(demo, 'demo');
const generalWorks = await emit(gen, 'work');

// demolition service image = first รื้อถอน photo
if (demo.length) {
  const out = await sharp(demo[0]).resize({ width: 1000, withoutEnlargement: true }).jpeg({ quality: 78, mozjpeg: true }).toBuffer();
  await writeFile('public/images/demolition.jpg', out);
}

await writeFile(
  'src/data/works.ts',
  `// generated by scripts/works-images.mjs — do not hand-edit\nexport const demolitionWorks = ${JSON.stringify(demolitionWorks, null, 2)};\nexport const generalWorks = ${JSON.stringify(generalWorks, null, 2)};\n`
);

await rm(SRC, { recursive: true, force: true }); // originals safe in image-originals/works
console.log(`demolition: ${demolitionWorks.length}, general: ${generalWorks.length}, src folder removed`);
