// generated by scripts/works-images.mjs — do not hand-edit
export const demolitionWorks = [
  "/images/works/demo-01.jpg",
  "/images/works/demo-02.jpg",
  "/images/works/demo-03.jpg",
  "/images/works/demo-04.jpg",
  "/images/works/demo-05.jpg",
  "/images/works/demo-06.jpg",
  "/images/works/demo-07.jpg",
  "/images/works/demo-08.jpg",
  "/images/works/demo-09.jpg"
];
export const generalWorks = [
  "/images/works/work-01.jpg",
  "/images/works/work-02.jpg",
  "/images/works/work-03.jpg",
  "/images/works/work-04.jpg",
  "/images/works/work-05.jpg",
  "/images/works/work-06.jpg",
  "/images/works/work-07.jpg",
  "/images/works/work-08.jpg",
  "/images/works/work-09.jpg",
  "/images/works/work-10.jpg",
  "/images/works/work-11.jpg",
  "/images/works/work-12.jpg",
  "/images/works/work-13.jpg",
  "/images/works/work-14.jpg",
  "/images/works/work-15.jpg"
];
